# Generated by Django 4.2 on 2023-06-24 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('active', models.BooleanField(default=False)),
                ('labtechnician', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G2000', models.CharField(blank=True, max_length=20, null=True)),
                ('G2000_x', models.CharField(blank=True, max_length=20, null=True)),
                ('GT9', models.CharField(blank=True, max_length=20, null=True)),
                ('GTI', models.CharField(blank=True, max_length=20, null=True)),
                ('NEO', models.CharField(blank=True, max_length=20, null=True)),
                ('ES', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('HB3', models.CharField(blank=True, max_length=20, null=True)),
                ('DFS', models.CharField(blank=True, max_length=20, null=True)),
                ('LFT', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('RFT', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('TFT', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('MAC', models.CharField(blank=True, max_length=20, null=True)),
                ('LGL', models.CharField(blank=True, max_length=20, null=True)),
                ('LIP', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('labtechnician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labtechnician.labtechnicianprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.laborder')),
            ],
        ),
        migrations.CreateModel(
            name='MicrobiologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Urine_FEME', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('RPR', models.CharField(blank=True, max_length=20, null=True)),
                ('Microscopy', models.CharField(blank=True, max_length=20, null=True)),
                ('AFB_ZN', models.CharField(blank=True, max_length=20, null=True)),
                ('AFB', models.CharField(blank=True, max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('labtechnician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labtechnician.labtechnicianprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.laborder')),
            ],
        ),
        migrations.CreateModel(
            name='HematologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FBE', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('FBC', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('Hb', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('Platelets', models.IntegerField(blank=True, null=True)),
                ('TWDC', models.IntegerField(blank=True, null=True)),
                ('ABO_Rh', models.CharField(blank=True, max_length=20, null=True)),
                ('Malaria', models.CharField(blank=True, max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('labtechnician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labtechnician.labtechnicianprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.laborder')),
            ],
        ),
        migrations.CreateModel(
            name='BiochemistryTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEA', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('CA1', models.CharField(blank=True, max_length=20, null=True)),
                ('CA5', models.CharField(blank=True, max_length=20, null=True)),
                ('CA9', models.CharField(blank=True, max_length=20, null=True)),
                ('PSA', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('AFP', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('Glucose', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('HIV1_2', models.CharField(blank=True, max_length=20, null=True)),
                ('HbA1c', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('HBsAg', models.CharField(blank=True, max_length=20, null=True)),
                ('H_pylori', models.CharField(blank=True, max_length=20, null=True)),
                ('Uric_Acid', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('Free_T4', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('labtechnician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labtechnician.labtechnicianprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.laborder')),
            ],
        ),
        migrations.CreateModel(
            name='AnatomicalPathologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Histology', models.TextField(blank=True, null=True)),
                ('Non_Gynae', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('labtechnician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='labtechnician.labtechnicianprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.laborder')),
            ],
        ),
    ]
