# Generated by Django 4.2 on 2023-06-24 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=30, null=True)),
                ('equipment_type', models.CharField(max_length=30, null=True)),
                ('manufacturer', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(max_length=30, null=True)),
                ('serial_number', models.CharField(max_length=30, null=True)),
                ('country_of_origin', models.CharField(max_length=30, null=True)),
                ('year_of_manufacture', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023, verbose_name='Year of Manufacture')),
                ('warranty_expired_date', models.DateTimeField(blank=True, null=True)),
                ('power_requirment', models.IntegerField()),
                ('spare_parts_available', models.BooleanField(default=False)),
                ('dispose', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('active', models.BooleanField(default=False)),
                ('material_manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('start_at', models.DateField(null=True)),
                ('end_at', models.DateField(null=True)),
                ('service_cost', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialmanager.inventory')),
                ('material_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materialmanager.materialmanagerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InvetoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('operable and in service', 'operable and in service'), ('operable and out of service', 'operable and out of service'), ('needs maintenace', 'needs maintenance'), ('not repairable', 'not repairable')], max_length=30)),
                ('reason', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='materialmanager.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relocation_department', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('department_contact_person', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materialmanager.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='manuals_available',
            field=models.ManyToManyField(to='materialmanager.manuals'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
