# Generated by Django 4.2 on 2023-06-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
