# Generated by Django 4.2 on 2023-06-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialmanager', '0003_inventory_clinical_department_inventory_manual_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='manual_file',
            field=models.FileField(null=True, upload_to='manuals/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='manuals_available',
            field=models.ManyToManyField(blank=True, to='materialmanager.manuals'),
        ),
    ]
