# Generated by Django 4.2 on 2023-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialmanager', '0004_alter_inventory_manual_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='warranty_expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
