# Generated by Django 4.2 on 2023-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.CharField(blank=True, choices=[('Addis Ababa', 'Addis Ababa'), ('Diredawa', 'Diredawa'), ('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Gambella', 'Gambella'), ('Harari', 'Harari'), ('Sidama', 'Sidama'), ('SNNP', 'SNNP'), ('SWEP', 'South West Ethiopian People')], max_length=20, null=True),
        ),
    ]
