# Generated by Django 4.1.7 on 2023-03-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
