# Generated by Django 4.1.3 on 2023-03-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_patient_address_patient_gender_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.TextField(null=True)),
                ('dosage', models.TextField(null=True)),
                ('instruction', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.doctorprofile')),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
            ],
        ),
    ]
