# Generated by Django 4.1.7 on 2023-03-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_prescribedmedicine_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='dosage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.doctorprofile')),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labtests', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.doctorprofile')),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.patient')),
            ],
        ),
    ]
