# Generated by Django 4.1.3 on 2023-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_pharmacistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedicine',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
