# Generated by Django 4.2 on 2023-06-24 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('active', models.BooleanField(default=False)),
                ('nurse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('temprature', models.IntegerField(blank=True, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('respirations', models.IntegerField(blank=True, null=True)),
                ('bloodsugar', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nurse.nurseprofile')),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterDeath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_time', models.TimeField(blank=True, null=True)),
                ('death_reason', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nurse.nurseprofile')),
                ('Patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterBirth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('middle_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('birth_weight', models.IntegerField()),
                ('birth_length', models.IntegerField()),
                ('mother_first_name', models.CharField(max_length=20, null=True)),
                ('mother_middle_name', models.CharField(max_length=20, null=True)),
                ('mother_last_name', models.CharField(max_length=20, null=True)),
                ('mother_date_of_birth', models.DateField(blank=True, null=True)),
                ('mother_nationality', models.CharField(max_length=20, null=True)),
                ('mother_occupation', models.CharField(max_length=20, null=True)),
                ('father_first_name', models.CharField(max_length=20, null=True)),
                ('father_middle_name', models.CharField(max_length=20, null=True)),
                ('father_last_name', models.CharField(max_length=20, null=True)),
                ('father_date_of_birth', models.DateField(blank=True, null=True)),
                ('father_nationality', models.CharField(max_length=20, null=True)),
                ('father_occupation', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nurse.nurseprofile')),
            ],
        ),
    ]
