# Generated by Django 4.2 on 2023-06-24 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyorder',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.patient'),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='imagingtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.imagingtype'),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='Cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.cashierprofile'),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.patient'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.patient'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='Cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.cashierprofile'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.patient'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='anatomical_pathology_test',
            field=models.ManyToManyField(blank=True, to='doctor.anatomicalpathologytest'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='biochemistry_test',
            field=models.ManyToManyField(blank=True, to='doctor.biochemistrytest'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='fasting',
            field=models.ManyToManyField(blank=True, to='doctor.fasting'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='hematology_test',
            field=models.ManyToManyField(blank=True, to='doctor.hematologytest'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='microbiology_test',
            field=models.ManyToManyField(blank=True, to='doctor.microbiologytest'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='profile_test',
            field=models.ManyToManyField(blank=True, to='doctor.profiletest'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='sample_type',
            field=models.ManyToManyField(blank=True, to='doctor.sampletype'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='Specalization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorspecalization'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
